# UCG-Ultra IPS/IDS Configuration
# Comprehensive Intrusion Prevention and Detection System setup
# for secure home lab environment

metadata:
  version: "1.0"
  created: "2024-01-20"
  description: "Advanced IPS/IDS configuration for UCG-Ultra"
  integration: "ELK Stack Security Monitoring"

# Global IPS/IDS Settings
global_settings:
  ips_enabled: true
  ids_enabled: true
  mode: "prevention"  # detection, prevention, or hybrid
  sensitivity_level: "balanced"  # conservative, balanced, aggressive
  packet_capture:
    enabled: true
    buffer_size: "256MB"
    max_file_size: "100MB"
    retention_days: 7
  
  # Performance settings
  performance:
    max_rules: 50000
    rule_loading_threads: 4
    packet_processing_threads: 8
    flow_timeout: 300
    max_pending_packets: 65535

# Signature Management
signature_management:
  automatic_updates:
    enabled: true
    update_frequency: "4 hours"
    sources:
      - "emerging_threats"
      - "snort_community"
      - "custom_signatures"
    
  signature_categories:
    malware:
      enabled: true
      action: "drop_alert"
      priority: "high"
      categories:
        - "trojan_activity"
        - "malware_cnc"
        - "botnet_activity"
        - "spyware_activity"
    
    vulnerability_exploits:
      enabled: true
      action: "drop_alert"
      priority: "high"
      categories:
        - "exploit_kit"
        - "shellcode_detect"
        - "buffer_overflow"
        - "remote_code_execution"
    
    web_attacks:
      enabled: true
      action: "drop_alert"
      priority: "medium"
      categories:
        - "sql_injection"
        - "xss_attack"
        - "directory_traversal"
        - "command_injection"
        - "file_inclusion"
    
    network_attacks:
      enabled: true
      action: "drop_alert"
      priority: "high"
      categories:
        - "dos_attack"
        - "ddos_attack"
        - "scan_detection"
        - "brute_force"
    
    policy_violations:
      enabled: true
      action: "alert"
      priority: "medium"
      categories:
        - "inappropriate_content"
        - "p2p_activity"
        - "suspicious_traffic"

# Custom Signatures
custom_signatures:
  homelab_specific:
    - signature_id: "HL_001"
      name: "SSH Brute Force Detection"
      rule: |
        alert tcp any any -> $HOME_NET 22 (
          msg:"SSH Brute Force Attempt Detected";
          flow:to_server,established;
          content:"SSH-";
          detection_filter:track by_src,count 5,seconds 60;
          classtype:attempted-admin;
          sid:1001;
          rev:1;
        )
      action: "drop_alert"
      enabled: true
    
    - signature_id: "HL_002"
      name: "Cryptocurrency Mining Detection"
      rule: |
        alert tcp $HOME_NET any -> any any (
          msg:"Cryptocurrency Mining Activity";
          content:"stratum+tcp";
          nocase;
          classtype:policy-violation;
          sid:1002;
          rev:1;
        )
      action: "drop_alert"
      enabled: true
    
    - signature_id: "HL_003"
      name: "DNS Tunneling Detection"
      rule: |
        alert udp $HOME_NET any -> any 53 (
          msg:"Possible DNS Tunneling Activity";
          content:"|01 00 00 01|";
          byte_test:2,>,100,12;
          classtype:policy-violation;
          sid:1003;
          rev:1;
        )
      action: "alert"
      enabled: true
    
    - signature_id: "HL_004"
      name: "IoT Device Anomaly"
      rule: |
        alert tcp $IOT_NETWORK any -> !$HOME_NET any (
          msg:"IoT Device Unusual Outbound Connection";
          flow:to_server,established;
          threshold:type both,track by_src,count 10,seconds 300;
          classtype:policy-violation;
          sid:1004;
          rev:1;
        )
      action: "alert"
      enabled: true

# Interface Configuration
interface_configuration:
  monitoring_interfaces:
    - interface: "wan"
      enabled: true
      mode: "tap"
      direction: "both"
      promiscuous: true
      
    - interface: "lan_trunk"
      enabled: true
      mode: "tap"
      direction: "both"
      vlan_monitoring:
        - vlan_id: 10
          name: "management"
          monitoring_level: "high"
        - vlan_id: 20
          name: "lan"
          monitoring_level: "medium"
        - vlan_id: 30
          name: "dmz"
          monitoring_level: "high"
        - vlan_id: 40
          name: "guest"
          monitoring_level: "low"

# Threat Intelligence Integration
threat_intelligence:
  enabled: true
  sources:
    abuse_ipdb:
      enabled: true
      api_key: "${ABUSEIPDB_API_KEY}"
      confidence_threshold: 75
      cache_duration: "24 hours"
    
    virustotal:
      enabled: true
      api_key: "${VIRUSTOTAL_API_KEY}"
      scan_files: true
      scan_urls: true
      cache_duration: "12 hours"
    
    emerging_threats:
      enabled: true
      feed_type: "reputation"
      categories:
        - "compromised_hosts"
        - "malware_domains"
        - "tor_exit_nodes"
      update_frequency: "1 hour"
    
    custom_feeds:
      - name: "internal_threat_intel"
        url: "https://internal.homelab.local/threat-feed.json"
        format: "json"
        update_frequency: "30 minutes"
        authentication:
          type: "api_key"
          key: "${INTERNAL_FEED_KEY}"

# Behavioral Analysis
behavioral_analysis:
  enabled: true
  learning_period: "7 days"
  
  anomaly_detection:
    network_flow:
      enabled: true
      baseline_deviation_threshold: 3.0
      metrics:
        - "connection_rate"
        - "data_volume"
        - "protocol_distribution"
        - "geographic_distribution"
    
    application_behavior:
      enabled: true
      track_applications:
        - "http"
        - "https"
        - "dns"
        - "smtp"
        - "ssh"
      anomaly_threshold: 2.5
    
    user_behavior:
      enabled: true
      track_by_ip: true
      track_by_user: false  # No user authentication on UCG-Ultra
      behavioral_metrics:
        - "access_patterns"
        - "resource_usage"
        - "time_based_activity"

# Machine Learning Models
ml_models:
  malware_detection:
    enabled: true
    model_type: "ensemble"
    features:
      - "packet_size_distribution"
      - "inter_arrival_times"
      - "protocol_sequences"
      - "payload_entropy"
    update_frequency: "weekly"
    accuracy_threshold: 0.95
  
  botnet_detection:
    enabled: true
    model_type: "clustering"
    features:
      - "communication_patterns"
      - "domain_generation_algorithms"
      - "c2_communication_signatures"
    detection_threshold: 0.8
  
  zero_day_detection:
    enabled: true
    model_type: "anomaly_detection"
    baseline_training_period: "30 days"
    anomaly_threshold: 2.0

# Response Actions
response_actions:
  immediate_response:
    high_severity:
      actions:
        - "drop_packet"
        - "block_source_ip"
        - "alert_administrators"
        - "capture_packets"
      duration: "1 hour"
      escalation_threshold: 5
    
    medium_severity:
      actions:
        - "alert_log"
        - "rate_limit_source"
        - "monitor_closely"
      duration: "30 minutes"
      escalation_threshold: 10
    
    low_severity:
      actions:
        - "log_event"
        - "update_statistics"
      escalation_threshold: 50
  
  automated_remediation:
    ip_reputation_blocking:
      enabled: true
      reputation_threshold: 25
      block_duration: "24 hours"
      whitelist_check: true
    
    rate_limiting:
      enabled: true
      trigger_threshold: 100  # connections per minute
      limit_rate: 10  # connections per minute
      duration: "15 minutes"
    
    quarantine:
      enabled: true
      trigger_conditions:
        - "malware_detected"
        - "c2_communication"
        - "data_exfiltration"
      quarantine_vlan: 999
      duration: "until_manual_review"

# Alert Configuration
alerting:
  notification_channels:
    syslog:
      enabled: true
      server: "192.168.10.3"
      port: 514
      protocol: "udp"
      facility: "local0"
      severity_mapping:
        high: "error"
        medium: "warning"
        low: "info"
    
    email:
      enabled: true
      smtp_server: "smtp.homelab.local"
      from_address: "ips-alerts@homelab.local"
      recipients:
        - "admin@homelab.local"
        - "security@homelab.local"
      severity_threshold: "medium"
    
    snmp:
      enabled: true
      community: "homelab_monitoring"
      manager_ip: "192.168.10.3"
      port: 162
    
    webhook:
      enabled: true
      url: "https://192.168.10.3:5601/api/alerts/webhook"
      authentication:
        type: "bearer_token"
        token: "${KIBANA_WEBHOOK_TOKEN}"
      retry_attempts: 3

# Logging Configuration
logging:
  log_level: "info"
  log_rotation:
    enabled: true
    max_size: "100MB"
    max_files: 10
    compression: true
  
  log_categories:
    alerts:
      enabled: true
      include_packet_data: true
      max_packet_size: "1500 bytes"
    
    flows:
      enabled: true
      log_frequency: "5 minutes"
      include_metadata: true
    
    statistics:
      enabled: true
      collection_interval: "1 minute"
      retention_period: "30 days"
    
    performance:
      enabled: true
      metrics:
        - "cpu_usage"
        - "memory_usage"
        - "packet_processing_rate"
        - "rule_processing_time"

# Tuning Parameters
tuning:
  memory_settings:
    packet_buffer_size: "512MB"  
    flow_cache_size: "256MB"
    rule_cache_size: "128MB"
    
  processing_limits:
    max_concurrent_flows: 100000
    max_packet_rate: 1000000  # packets per second
    max_bandwidth: "10Gbps"
    
  timeout_settings:
    tcp_timeout: 300
    udp_timeout: 30
    icmp_timeout: 30
    flow_timeout: 600

# Integration Settings
integrations:
  elk_stack:
    enabled: true
    elasticsearch_hosts:
      - "192.168.10.3:9200"
    index_template: "ucg-ultra-ips"
    pipeline: "ucg-ultra-enrichment"
    
  threat_hunting:
    enabled: true
    hunt_queries:
      - name: "lateral_movement"
        query: "src_ip:192.168.*.* AND dest_ip:192.168.*.* AND alert.category:network-scan"
        frequency: "hourly"
      - name: "data_exfiltration"
        query: "alert.category:policy-violation AND bytes_out:>1000000"
        frequency: "15 minutes"
  
  incident_response:
    enabled: true
    playbooks:
      - trigger: "malware_detected"
        actions:
          - "isolate_host"
          - "collect_forensics"
          - "notify_ir_team"
      - trigger: "credential_theft"
        actions:
          - "force_password_reset"
          - "audit_account_access"
          - "increase_monitoring"

# Compliance and Reporting
compliance:
  frameworks:
    - "NIST_CSF"
    - "ISO_27001"
    - "CIS_Controls"
  
  reporting:
    enabled: true
    schedules:
      daily:
        - "security_summary"
        - "top_threats"
        - "performance_metrics"
      weekly:
        - "trend_analysis"
        - "rule_effectiveness"
        - "false_positive_rate"
      monthly:
        - "compliance_status"
        - "threat_landscape"
        - "system_recommendations"
    
    delivery:
      formats:
        - "pdf"
        - "json" 
        - "csv"
      recipients:
        - "security-team@homelab.local"
        - "management@homelab.local"

# Maintenance and Updates
maintenance:
  scheduled_tasks:
    - name: "signature_update"
      frequency: "daily"
      time: "02:00"
      actions:
        - "download_signatures"
        - "validate_signatures"
        - "reload_rules"
    
    - name: "performance_optimization"
      frequency: "weekly"
      time: "sunday_03:00"
      actions:
        - "analyze_rule_performance"
        - "optimize_rule_order"
        - "clean_old_logs"
    
    - name: "ml_model_retrain"
      frequency: "monthly"
      time: "first_sunday_04:00"
      actions:
        - "collect_training_data"
        - "retrain_models"
        - "validate_accuracy"
        - "deploy_models"
  
  backup:
    enabled: true
    frequency: "daily"
    retention: "30 days"
    backup_items:
      - "configuration"
      - "custom_rules"
      - "ml_models"
      - "threat_intelligence_data"